# Generated by Django 4.2.13 on 2026-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedido_alter_produto_options_loja_itempedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='atributos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
